### ISSUE TITLE
Generate an executable file ( .exe file ) and add it in a folder named builds

### ISSUE THREAD

**Issue by krishnachaitanya0107** [krishnachaitanya0107/FaceDetector#1]
Description

- Create a build file using PyInstaller . You can follow the below wiki for guidance

  https://datatofish.com/executable-pyinstaller/

- Test out the build and look for any errors if any

- Create a folder named builds and add the exe file inside it

**Comment by shubhamrawat090** [comment]
Hi @krishnachaitanya0107 can you assign me this?

**Comment by Sougata2** [comment]
Hi @krishnachaitanya0107 kindly assign me this issue to me.
